### ISSUE TITLE
Can we make this work on Linux version of Matlab?

### ISSUE THREAD

**Issue by caballero03** [alekseikukin/matscad#1]
I am a bit new to Matlab and I have been trying to hack this to work on Linux but it still says either:
/bin/bash: start: command not found
/bin/bash: C:\Program Files\OpenSCAD\openscad.exe: command not found
or
/bin/bash: start: command not found
/bin/bash: /usr/bin/openscad.exe: No such file or directory

depending on how far I get. I am struggling to get it to let go of the extension.

My OpenSCAD installed program is at "/usr/bin/openscad". There is no extension on the executable.

Do you have any ideas of how I can change this?

**Comment by alekseikukin** [comment]
Good day!
To be honest I never worked with linux, but as I see, try change file "cmdOpenSCAD.m" as:

```
% scadfolder = GetParamFromFile('path');
% while ~isempty(varargin)
%     switch lower(varargin{1})
%         case 'scadfolder'
%             scadfolder = varargin{2};
%         otherwise
%     end
%     varargin(1:2) = [];
% end
% path_cd = cd; % save current location
cmd = ['openscad' comand ]; % build command
status = system(cmd);  % run command
% cd(path_cd); % go back to first folder
```

**Comment by caballero03** [comment]
Thank you for that lead. I am trying something like this:

```
% Detect operating system
if ispc
    cmd = ['"'  scadfolder 'openscad.exe" ' comand ]; % build command
elseif isunix
    cmd = ['"'  scadfolder 'openscad" ' comand ];
else
    disp('Platform not supported')
end
```

https://www.mathworks.com/help/matlab/ref/ispc.html

In that file you mention. We'll see what happens.

**Comment by alekseikukin** [comment]
It looks like you don't need folder of openscad in command line.

**Comment by caballero03** [comment]
I got it working. I had to specify my system libraries for Qt because Matlab was trying to run OpenSCAD using its own Qt libraries.

I added a line in a startup.m file in my userpath (the MATLAB) folder. Like this:
```setenv('LD_LIBRARY_PATH', ['/usr/lib/x86_64-linux-gnu:',getenv('LD_LIBRARY_PATH')]);```

Then, my changes to matscad were:

In set_openscad_folder.m:
```
% change path
if ispc
    [file_name, path2openscad] = uigetfile('*.exe',...
        'Select openscad.exe file','C:\Program Files\OpenSCAD\openscad.exe');
    if ~isempty(path2openscad) && string(file_name) == "openscad.exe"
        SetOpenSCAD('path', path2openscad);
    else
        disp('folder was not selected')
    end
elseif isunix
    [file_name, path2openscad] = uigetfile('*',...
        'Select openscad executable','/usr/bin/openscad');
    if ~isempty(path2openscad) && string(file_name) == "openscad"
        SetOpenSCAD('path', path2openscad);
    else
        disp('folder was not selected')
    end
end
```

And in the file you had mentioned, cmdOpenSCAD.m:
```
% Detect operating system
if ispc
    cmd = ['"'  scadfolder 'openscad.exe" ' comand ]; % build command
elseif isunix
    cmd = ['"'  scadfolder 'openscad" ' comand ];
else
    disp('Platform not supported')
end
```
Like I had mentioned before. 

I know this doesn't help you, but it may help someone else trying to do the same thing. I don't know how to do a pull request but I could figure it out if you wanted to include this in your matscad system.

Thank you for your help with this.

**Comment by alekseikukin** [comment]
Thanks!
