### ISSUE TITLE
Integrate manifold Library into command line prompt

### ISSUE THREAD

**Issue by BK524** [alekseikukin/matscad#2]
Hi Aleksei,
Do you think it's possible to integrate the new manifold library into the MatSCAD toolbox? It's very helpful but it would be great to be able to use the colour/texture export capability provided by manifold. I have it active in the nightly version but it doesn't seem to be utilised when I run MatSCAD.
Cheers
Ben

**Comment by alekseikukin** [comment]
Hi!
MatSCAD only generates script files for OpenSCAD. It should use the same parameters. Have you tried activating the GUI to check what's going on?
If you need a specific command prompt, could you please share it? I haven't used manifold before.

**Comment by BK524** [comment]
Hi Aleksei, sorry for the delayed reply.
Manifold is an optional toolbox that replaces the CGAL render on the most recent developmental snapshots. It can be enabled in the preferences tab when using the GUI. It introduces a few new capabilities (such as colour export) whilst, from my understanding, being generally more speedy at rendering. However, as using MatSCAD bypasses the GUI, manifold does not activate when running via MatSCAD. This seems to be a general issue with running manifold from a command line prompt: https://www.reddit.com/r/openscad/comments/1g2tk83/command_line_doesnt_use_manifold/

Will it be as simple as adding "enable-manifold" to the OpenSCAD_cmd function?
Cheers!

**Comment by alekseikukin** [comment]
Hi!
Please check last release...
